name: Windows

on:
  push:
    branches: master

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: download_plugin
      run: |
        echo "I am running from master branch!"
        echo "Fetching Neuropixels plugin..."
        LATEST_VERSION=$(curl -s https://api.bintray.com/packages/open-ephys-gui-plugins/neuropixels-pxi/neuropixels-pxi-win/versions/_latest | jq '.name')
        LATEST_VERSION="${LATEST_VERSION:1:${#LATEST_VERSION}-2}"
        echo -e "\nLatest version: $LATEST_VERSION"
      shell: bash