name: Windows

on:
  push:
    branches: test

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
        build_dir: "Build/Release"
        repo: "Binaries-Testing"
        package: "Windows"
        version: "0.4.6" 
      run: |
        echo "I am running from master branch!"
        user_info="$bintrayUser:$bintrayApiKey"
        cd $build_dir
        echo "Fetching Neuropixels plugin..."
        LATEST_VERSION=$(curl -s -X GET https://api.bintray.com/packages/$bintrayUser/neuropixels-pxi/neuropixels-pxi-win/versions/_latest | jq '.name')
        LATEST_VERSION="${LATEST_VERSION:1:${#LATEST_VERSION}-2}"
        filename=$( curl -s --user $user_info -X GET https://api.bintray.com/packages/${bintrayUser}/neuropixels-pxi/neuropixels-pxi-win/versions/$LATEST_VERSION/files | jq '.[] | .name')
        filename="${filename:1:${#filename}-2}"
        curl -L https://dl.bintray.com/${bintrayUser}/${neuropixels-pxi}/${filename} > ${filename}
        powershell Expand-Archive -Path ${filename} -DestinationPath plugins/
        zip=${bintrayUser}-${package}-${version}.zip
        powershell Compress-Archive . ${zip}
        curl -T $zip --user $user_info https://api.bintray.com/content/${bintrayUser}/${repo}/${package}/${version}/${zip}
        curl -X POST --user $user_info https://api.bintray.com/content/${bintrayUser}/${repo}/${package}/${version}/publish
      shell: bash