name: Windows

on:
  push:
    branches: master

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: download_plugin
      run: |
        python .github/test.py
      shell: bash