name: Windows

on:
  push:
    branches: test

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      env:
        branch: ${{ github.head_ref }}
      shell: bash
      run: echo $branch
    - name: configure
      run: |
        powershell Compress-Archive . test1.zip
        ls
      shell: bash
