name: Windows

on:
  push:
    branches: test

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        echo "I am running from master branch!"
      shell: bash
