name: Windows

on: [push]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: package
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run : |
        gui_ver=0.4.5
        zipfile=open-ephys-${gui_ver}-windows.zip
        mkdir plugins
        touch plugins/test.txt
        powershell Compress-Archive -Path "plugins" -DestinationPath ${zipfile}
        if [ -d "shared" ]
        then
          powershell Compress-Archive -U -Path "shared" -DestinationPath ${zipfile}
        fi
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-windows/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-windows/$gui_ver/publish
      shell: bash